### ISSUE TITLE
Side by side fields and custom JSX validation 

### ISSUE THREAD

**Issue by harshit9715** [fateh999/react-native-paper-form-builder#40]
Is there a way I can achieve _flex-direction 'row'_ for form inputs? (trying to place components side by side)

I was able to achieve the UI functionality by returning custom JSX for 1 field but I don't understand how to add validation to _type: 'custom',_. Can you please add validation in your "Remember me" button example or a different example for custom component validation?

**Comment by fateh999** [comment]
To get multi column inputs in a row, you don't need to use custom jsx, just pass an array instead of a config object, in case you want custom input just use custom jsx in the config object.


[Check this example](https://github.com/fateh999/react-native-paper-form-builder/blob/master/example/AdvancedExample.tsx)
