### ISSUE TITLE
@All i would like to know your feedback and suggestions regarding this library so i can improve it. 

### ISSUE THREAD

**Issue by fateh999** [fateh999/react-native-paper-form-builder#8]

**Comment by ArjArav98** [comment]
Really good stuff. I've been searching for a dropdown component in the react-native-paper style. It would really help if you can give the ability to just import one component at a time (such as dropdown) in order to increase usability. It's a bit disadvantageous to import the entire 'FormBuilder' component.

**Comment by ArjArav98** [comment]
Leaving a star for your good work :)

**Comment by fateh999** [comment]
Thanks @ArjArav98 yes exporting some components from form builder to be able to use it alone is on the cards, surely will be doing in this repo or will create a seperate library for that.

**Comment by farandal** [comment]
Seems very promising! But I'm having problems with the basic implementation. 
I can't get the values from the form, I'm doing something wrong?
Thanks!
https://www.evernote.com/l/AB-14O2zBflH_p_R4m7CmD1w_S38AaJhYUk

**Comment by farandal** [comment]
@fateh999 I still think your project is awesome, but still require quite some work.
I've tried to fork the project, and running it, but I have had too many issues. 

This is so far:

First,React Native 0.62 is not compatible with your code, and now 0.63 is rolling out. 
React 0.62 do not requires manual linking of libraries, so I had to unlink it. 
Please take this in consideration to remove the part where you do the manual linking later. 

```react-native unlink react-native-vector-icons```

Second, seems to be some missing files in your project, related to the Test framework, 
in order to run the project I had to remove all references to FormBuilderTests

Third, 
There is an issue regarding the pods for ios, as it seems your code is incompatible with React 0.62
Please refer to this solution steps:
https://stackoverflow.com/a/60881827/6319266

The solution that worked for me were this changes:
```platform :ios, '9.0'```
to
```platform :ios, '10.0'```

```pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon```
To
```pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"```

And commented out the blocks related to the Test suite. 
```
#  target 'reactNativePaperFormBuilderTests' do
#    inherit! :search_paths
    # Pods for testing
#  end
```

Also I didn't see the meaning to have the TvIOS project around there... 

Fourth

remove podfile.lock
pod repo update

Fifth

For some reason, npm install is not really installing many of the required depenancies. I'm not really sure why yet, but I solved the issue installing them manually. 
```npm install ```
```npm install  react react-hook-form  react-native react-native-paper react-native-vector-icons --save```
```npm audit fix ```

After all this I was able to run the project, 
But more errors came up.
https://www.evernote.com/l/AB-REyOx5cRHOaWIjrYH7e87XmMddICyc68

So, at this point, I just decided to drop further research for now!
Please, try to fix some of this issues! It's an awesome project, but still far from production usage. 

Cheers Mate!

**Comment by fateh999** [comment]
@farandal Thanks for trying out the library, i am actually working on it, i will be moving the React Native code to a Example folder so as to make the code of library be independent of the version of React Native. However it will not work with React Native version 0.58 or less. Also i checked your image sample it didn't look like you were doing anything wrong it is just that the issue could be from the versions of React Native and React Hook Form.

**Comment by Alarees** [comment]
Hi, y can add autofocus for input field using `onSubmitEditing` as in [Here](https://dev.to/elaziziyoussouf/forms-in-react-native-the-right-way-4d46)
